name: Publish Docker container

on:
  push:
    branches:
      - dev

  release:
    types: [published]
    tags: [ 'v*.*.*' ]

  workflow_dispatch:

jobs:
  push_to_registry:
    if: github.repository == 'NationalGenomicsInfrastructure/umi-injector'
    name: Push Docker image to Docker Hub / GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Change repo name to lowercase
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename ${GITHUB_REPOSITORY,,})" >> ${GITHUB_ENV}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Push dev image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        if: github.event_name != 'release'  #push or manual dispatch
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:dev
            ghcr.io/${{ env.REPO_LOWERCASE }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
      - name: Push release image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        if: github.event_name == 'release'
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOTITLE_LOWERCASE }}:latest
            ghcr.io/${{ env.REPO_LOWERCASE }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ env.REPO_LOWERCASE }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWERCASE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
